# This is a basic workflow to help you get started with Actions

name: LighouseMonitor

# Controls when the workflow will run
on:
  schedule:
    - cron:  '0/30 * * * *'
  workflow_dispatch:

jobs:
  check_traffic_package: 
    runs-on: ubuntu-latest
    steps:
      - name: get instance list
        uses: docker://mrlee326/lhbin
        with: 
          args: list
        env: 
          SECRET_ID: ${{ secrets.LIGHTHOUSE_SECRET_ID }}
          SECRET_KEY:  ${{ secrets.LIGHTHOUSE_SECRET_KEY }}
      
