# This is a basic workflow to help you get started with Actions

name: LighouseMonitor

# Controls when the workflow will run
on:
  schedule:
    - cron:  '0/30 * * * *'
  workflow_dispatch:

jobs:
  list_all_instances: 
    runs-on: ubuntu-latest
    outputs:
      instances: ${{ steps.get_instance_list.outputs }}
    steps:
      - name: get instance list
        id: get_instance_list
        uses: docker://mrlee326/lhbin
        with: 
          args: list
        env: 
          SECRET_ID: ${{ secrets.LIGHTHOUSE_SECRET_ID }}
          SECRET_KEY:  ${{ secrets.LIGHTHOUSE_SECRET_KEY }}
  check_traffic_packages:
    runs-on: ubuntu-latest
    needs: list_all_instances
    steps:
      - run: echo ${{needs.list_all_instances.outputs.instances}}
      
